[package]
authors = ["Brian Anderson <banderson@mozilla.com>"]
name = "fancy_flocks"
version = "0.1.0"

[dependencies]
fs2 = "0.4.1"
log = "0.3.8"
rand = "0.3.15"

[dev-dependencies]
tempdir = "0.3.7"
